In [1]:
import numpy as np

In [7]:
escalar = 5.95
vector = np.array([3,4,5])
matriz = np.array([[1,2],[3,4],[5,6]]) 

In [5]:
A = matriz + vector
print(A)

ValueError: operands could not be broadcast together with shapes (3,2) (4,) 

In [9]:
A = matriz.T + vector
print(A)

[[ 4  7 10]
 [ 5  8 11]]


In [11]:
# Matriz 3x2, mientras que su transpuesta es 2x3, entonces las suma extiende nuestro vector para poder hacer la suma
# es decir la suma seria: matriz + [[3,4,5],[3,4,5]], "replica el vector para completer hacia la matriz", esto es 
# llamado broadcasting

In [13]:
# En la suma una matriz con un escalar, internamente se realiza broadcasting, dado que se crea una matriz del tamaño
# de la primera y se "rellena" cada entrada con el escalar 
A = matriz + 42
print(A)

[[43 44]
 [45 46]
 [47 48]]


In [14]:
D = matriz + np.array([[42],[42], [42]]) # Ejemplo más claro de que se está haciendo broadcastoing
print(D)

[[43 44]
 [45 46]
 [47 48]]
