In [1]:
import numpy as np

In [4]:
escalar = 5.679
vector = np.array([1,2,3])
matriz = np.array([[1,2,3],[4,5,6]])
tensor = np.array([
    [[1,2,3],[4,5,6],[6,7,8]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[21,22,23],[24,25,26],[27,28,29]],
    [[21,22,23],[24,25,26],[27,28,29]],
]
)

In [5]:
vector.shape

(3,)

In [6]:
print(vector)

[1 2 3]


In [7]:
len(vector)

3

In [8]:
matriz.shape

(2, 3)

In [9]:
len(matriz)

2

In [12]:
print(matriz.size)

6


In [13]:
tensor.shape

(4, 3, 3)

In [14]:
# Utilidades de un tensor
## Pensar en la evolución de una matriz a través del tiempo
## Si una matriz es una foto, el tensor puede ser un video

In [16]:
vector_cero = np.array([0,0,0])
print(vector_cero)
vector_cero.shape

[0 0 0]


(3,)

In [17]:
vector_canonico_x = np.array([1,0])
print(vector_canonico_x)
vector_canonico_x.shape

[1 0]


(2,)

In [18]:
vector_canonico_y = np.array([0,1])
print(vector_canonico_y)
vector_canonico_y.shape

[0 1]


(2,)

In [21]:
matriz = np.array([[0,0,1],[0,1,0],[1,0,0]])
print(matriz)
matriz.shape

[[0 0 1]
 [0 1 0]
 [1 0 0]]


(3, 3)

In [27]:
tensor = np.array([
    [[0,0,0],[0,0,0],[0,0,0]],
    [[0,0,1],[0,1,0],[1,0,0]],
    [[0,1,1],[1,1,0],[1,0,1]],
    [[1,1,1],[1,1,1],[1,1,1]],
    [[0,0,2],[0,2,0],[2,0,0]],
])
print(tensor)
tensor.shape

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 1]
  [0 1 0]
  [1 0 0]]

 [[0 1 1]
  [1 1 0]
  [1 0 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[0 0 2]
  [0 2 0]
  [2 0 0]]]


(5, 3, 3)