In [1]:
import numpy as np

In [20]:
escalar = 5.679
vector = np.array([2,3])
matriz = np.array([[1,2],[3,4],[5,6]])
print(matriz)
print(vector)

[[1 2]
 [3 4]
 [5 6]]
[2 3]


In [10]:
A = matriz * vector # Matriz (3x2) * vector (2) = 3x2, ejemplo de Broadcasting


In [13]:
B = matriz.dot(vector) # Matriz (3x2) dot(vector (2,)) = 3,  [1x2 + 3x3][3x2 + 4x3][5x2 + 6x3]

In [5]:
print(A) 

[[ 2  6]
 [ 6 12]
 [10 18]]


In [6]:
print(B) 

[ 8 18 28]


In [11]:
C = vector.dot(np.array([10,20]))

In [12]:
print(C)

80


In [14]:
# Funcion producto interno o producto punto:
B = matriz.dot(vector)
C = np.dot(matriz,vector)
print(B)
print(" ")
print(C)

[ 8 18 28]
 
[ 8 18 28]


In [22]:
# Conmuta el producto interno?
matriz = np.array([[2,90],[-5,10]])
D = np.dot(matriz,vector)
E = np.dot(vector,matriz)
print(D)
print(" ")
print(E)

[274  20]
 
[-11 210]
