In [1]:
# Transponer una matriz es "intercambiar" las filas por las columnas
# Si se tiene una vector, al transponerlo se obtiene un vector columna
# La transposicion de una matriz 3x2 es una matriz 2x3 en donde la diagonal se mantiene igual
 

In [2]:
import numpy as np

In [3]:
escalar = 5.95
vector = np.array([3,4,5,6])
matriz = np.array([[1,2],[3,4],[5,6]])
tensor = np.array([
     [[1,2,3,30], [4,5,6,31], [7,8,9,32]],
    [[11,12,13,33], [14,15,16,34], [17,18,19,35]],
    [[21,22,23,36], [24,25,26,37], [27,28,29,38]]
])


In [4]:
escalar_t = escalar.T #No tiene filas ni columnas

AttributeError: 'float' object has no attribute 'T'

In [6]:
vector_t = vector.T
print(vector_t)

[3 4 5 6]


In [15]:
matriz_t = matriz.T
print(matriz)
print("######")
print(matriz_t)

[[1 2]
 [3 4]
 [5 6]]
######
[[1 3 5]
 [2 4 6]]


In [11]:
print(matriz.shape)

(3, 2)


In [12]:
print(matriz_t.shape)

(2, 3)


In [14]:
tensor_t = tensor.T
print(tensor)
print("######")
print(tensor_t)

[[[ 1  2  3 30]
  [ 4  5  6 31]
  [ 7  8  9 32]]

 [[11 12 13 33]
  [14 15 16 34]
  [17 18 19 35]]

 [[21 22 23 36]
  [24 25 26 37]
  [27 28 29 38]]]
######
[[[ 1 11 21]
  [ 4 14 24]
  [ 7 17 27]]

 [[ 2 12 22]
  [ 5 15 25]
  [ 8 18 28]]

 [[ 3 13 23]
  [ 6 16 26]
  [ 9 19 29]]

 [[30 33 36]
  [31 34 37]
  [32 35 38]]]


In [16]:
print(tensor.shape)

(3, 3, 4)


In [17]:
print(tensor_t.shape)

(4, 3, 3)


In [18]:
matriz_t_t = matriz_t.T
print(matriz_t_t)

[[1 2]
 [3 4]
 [5 6]]


In [19]:
# La transpuesta de una matriz transpuesta es la matriz original

In [20]:
# Suma de matriz definida para elementos del mismo tamaño

In [34]:
A = matriz
B = matriz_t
# C = A+B

In [22]:
B = np.array([[10,9], [8,7], [6,5]])
C = A+B
print(A)
print(B)
print(C)

[[1 2]
 [3 4]
 [5 6]]
[[10  9]
 [ 8  7]
 [ 6  5]]
[[11 11]
 [11 11]
 [11 11]]


In [33]:
D = matriz + escalar
print(D)

[[ 6.95  7.95]
 [ 8.95  9.95]
 [10.95 11.95]]


In [32]:
A = np.array([[20,9,5],[0,0,2],[7,1,-10]])
B = A.T
print(A)
print(" ")
print(B)

[[ 20   9   5]
 [  0   0   2]
 [  7   1 -10]]
 
[[ 20   0   7]
 [  9   0   1]
 [  5   2 -10]]


In [31]:
D = A + B
print(D)
print(" ")
print(D.shape)

[[ 40   9  12]
 [  9   0   3]
 [ 12   3 -20]]
 
(3, 3)
